### ISSUE TITLE
The message container is being closed (178485)

### ISSUE THREAD

**Issue by taroyutao** [Azure/iothub-explorer#39]
when we use iothub-explorer monitor-ops  --login "HostName=test.azure-devices.cn;SharedAccessKeyName=iothubowner;SharedAccessKey=123445......"

it sometimes automatic exit with errors：
Error: The message container is being closed (178485). TrackingId:78eb359c-268d-44bf-a9db-5fcbb8f7cbe4_B5, SystemTracker:NoSystemTracker, Timestamp:1/12/2018 3:23:59 AM

I notice it maybe a eventhub's problem：https://github.com/Azure/azure-event-hubs/issues/320

but I think it should be fixed in  iothub-explorer.

Any suggestions? 

thanks

**Comment by pierreca** [comment]
I believe the fix to this is to re-open the receiver links that have been detached (for each partition).

I'm tempted to consider this as low-priority since iothub-explorer is a debugging tool, not a thing that should be used in production (That's what the service sdk is for). Thoughts? would you like to contribute a fix to this issue?

**Comment by taroyutao** [comment]
I think add try catch the exception and Re initializing the object client, the error will be overcome.

**Comment by pierreca** [comment]
we're deprecating iothub-explorer, therefore this won't be fixed. closing.
