### ISSUE TITLE
Is there a iothub-receiver-app usable on the Linux console?

### ISSUE THREAD

**Issue by pboettch** [Azure/iothub-explorer#44]
# Context
- master-branch
- Linux (Debian testing and an embedded arm-based custom distribution)

# Description of the issue:
It's a question: Is it possible, with the iothub-explorer or any other iothub-sample/example, to act as a receiver/final consumer of messages sent to the device-queue? I used the monitoring-app, it works, but it does not suite my needs.

Thanks for any help.

**Comment by pierreca** [comment]
@pboettch 

a few questions to clarify: 
- are you asking about messages sent by a cloud service to a device (c2d) through IoT Hub or by a device to the cloud (d2c)? (in other words, which device queue are you talking about?)
- are you asking about "replacing" iothub to debug what is sent or a "peeking" feature that lets you see what's in the queue but keep using IoT Hub?
- are you asking about "simulated devices" receiving c2d messages?

**Comment by pboettch** [comment]
Thank you for your reply.

What I would like to do is to get the messages send by the device to the cloud. The device is using the _azure-iot-sdk-c_-libraries to send messages with MQTT via WebSockets into a device-queue (Using `IoTHubClient_LL_SendEventAsync`). There is a production application living in the cloud (not made by me) which is consuming the messages "somehow".

What I'm looking for is to read the messages from this device-queue (sent by the device) on a linux-terminal. I don't want to monitor them, I really want to get them out of the queue. 

The goal is to write a test application which verifies the round trip from the device's point of view.

**Comment by pierreca** [comment]
@pboettch 
OK I think I see what you mean - you want to consume messages coming from the devices and that are being "stored" on the event hubs partitions "behind" IoT Hub.

if you want to build a console application, the 2 officially supported SDKs for Event Hubs are here:

- [C# SDK] (https://github.com/azure/azure-event-hubs-dotnet)
- [Java SDK] (https://github.com/azure/azure-event-hubs-java)

Both of these will have samples that will show you how to build such a console app quickly. The other thing I could recommend specifically for node is to use Azure Functions (if you're OK with using a function instead of a real terminal) because they have Event Hubs bindings and can be written using node.

iothub-explorer just reads from the queue, receiving messages sent after it is started, but it does not manipulate the messages in the queue (doing checkpoints, etc, if you want to learn more about how these queues work this is a good read: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features)

I'm hesitant to point you to the node version of the Event hubs SDK because it's not being maintained (for now), and it's honestly neither stable nor production quality (never made it past preview, hasn't been updated in months). 

Please let me do know if that answers the question :)

**Comment by pboettch** [comment]
It looks like that I can directly use the "Event Hub-compatible endpoint" from my iothub-device. 

Now I need to learn how to build and run either the .NET-console-samples or the Java-samples from and in Linux.

**Comment by pboettch** [comment]
Wait, what's that? https://github.com/Azure/azure-event-hubs-c

**Comment by pboettch** [comment]
OK. I just PoC'd what I was looking for using `azure-event-hubs-c` and the Event-Hub-endpoint of my iothub-device. Thank you for your help, your few lines helped me a lot understanding how iothub and event-hubs work together. Sometimes it is the small, concrete summaries which are better than longer articles. Thanks again.
