### ISSUE TITLE
Getting an error running the iothubexplorer after the install

### ISSUE THREAD

**Issue by avidiyal** [Azure/iothub-explorer#51]
/usr/bin/env: ‘node’: No such file or directory

# Context
- **OS and version used:** <VERSION> 
- **Node.js version:** <VERSION> 
- **npm version:** <VERSION> 
- **list of installed packages:** <VERSION> 
- **cloned repo:** <VERSION> 

# Description of the issue:

# Console log of the issue:

# Code sample exhibiting the issue:

**Comment by pierreca** [comment]
@avidiyal without knowing the OS and how you run things, there's not much we can do to help.

- What OS are you running iothub-explorer on?
- What shell?
- Did you clone the repository or download the NPM Package?
- What version of node?
- What version of NPM?

This error would typically happen if:
- `/usr/bin/env` does not exist or `node` is not in your path
- for some reason the line endings of the files don't match what your OS expect (might happen with depending on your git configuration if you're cloning directly from the repo instead of using NPM to install the package).

I'm going to leave this issue open for a couple days to give you the opportunity to add more information but otherwise I'll close it as it seems to be an issue with your environment and not the package itself.

**Comment by avidiyal** [comment]
I did this  ln -s /usr/bin/nodejs /usr/bin/node and the error was gone. But now when I try to run monitor events it saus unauthorized error. I am connected to our proxy

**Comment by avidiyal** [comment]
I am running Ubuntu 16.04 and login was sucess. But anyother commands that I run returns me the below error "Error: UnauthorizedError: Unauthorized"

**Comment by pierreca** [comment]
some commands require running with the --login <connection-string> option because they cannot rely on the sas token that is saved when calling `iothub-explorer login`. monitor-events is one of them. 

I would suggest looking into the azure cli with the IoT Extension: https://github.com/azure/azure-iot-cli-extension - this will provide a much better experience that is integrated with all other azure features. we're in the process of deprecating iothub-explorer.
