### ISSUE TITLE
Unable to monitor client events through the utility.

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [Azure/iothub-explorer#8]
Getting following error log when executing the monitor command for client,

```
iothub-explorer monitor-events "myNodeClient" --login "LOGIN_DETAILS"

####OUTPUT###

Monitoring events from device myNodeClient...
/usr/local/lib/node_modules/iothub-explorer/node_modules/amqp10/lib/frames.js:54
  stream.write(buffer);
        ^

TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (/usr/local/lib/node_modules/iothub-explorer/node_modules/amqp10/lib/frames.js:54:9)
    at Connection.sendFrame (/usr/local/lib/node_modules/iothub-explorer/node_modules/amqp10/lib/connection.js:333:10)
    at ReceiverLink.Link.attach (/usr/local/lib/node_modules/iothub-explorer/node_modules/amqp10/lib/link.js:108:27)
    at ReceiverLink.Link._attemptReattach (/usr/local/lib/node_modules/iothub-explorer/node_modules/amqp10/lib/link.js:237:8)
    at Timeout._onTimeout (/usr/local/lib/node_modules/iothub-explorer/node_modules/amqp10/lib/link.js:225:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

```

**Comment by jonjander** [comment]
I had the same problem. I tried all Shared Access policies but non worked. Then i reinstalled iothub-explorer and used iothubowner connection string. And it worked :)

iothub-explorer monitor-events --login HostName=[URL].azure-devices.net;DeviceId=api;SharedAccessKey=[key];SharedAccessKeyName=iothubowner

**Comment by pierreca** [comment]
It's important to make a distinction between device connection strings (that contain the `DeviceId` property) and service connection strings (that contain the `SharedAccessKeyName` property). 

- Device connection strings are used to connect devices to IoT Hub and send/receive messages.
- Service connection strings are used to manage the device registry, twins, and send/receive messages from the devices.

@jonjander Looks like the connection string you suggest has both `DeviceId` and `SharedAccessKeyName`. In that case `DeviceId` will be ignored by iothub-explorer. 

@sanket-kulkarni-vmware Can you verify that you're using a service connection string?

Once we've established you're using a service connection string, maybe we can look at which policy you're using (the value associated with the `SharedAccessKeyName` property). This policy should have the "service connect" rights in the portal. iothubowner and service are both valid policies to listen to device messages:
![image](https://cloud.githubusercontent.com/assets/4979572/22564183/6b445578-e938-11e6-9108-49ec01c21776.png)

In any case, it's a bit of a shitty error so I'd be glad to understand more how you are connecting, or if you're connecting successfully and this happens later, when does it happen so that we can update to tool to provide a better error message.

**Comment by sanket-kulkarni-vmware** [comment]
@pierreca: Yes I am using the service connection string for monitoring the device messages. One strange thing I would like to mention here, not every time I get above error log(2-3 times out of 10).

**Comment by pierreca** [comment]
So it's transient then. Thanks for clarifying!
Looks like it happens in the underlying [amqp10](https://github.com/noodlefrenzy/node-amqp10) library (ping @noodlefrenzy @mbroadst FYI)
I'm going to dig into it, looks like the link might be attempting to automatically reattach even though we configure it not to do that. begs a couple of questions:
- why is it ignoring the `reattach` settings we set in `common/transport/amqp/amqp.js` (or are we setting those correctly?
-  Why is the link being detached in the first place?

@sanket-kulkarni-vmware a few more questions:
- what version of node and npm are you running?
- on what OS?
- would you mind setting the `DEBUG` environment variable to `*` and giving it another shot? it's going to spew a lot of output (including all AMQP traces) that should help us narrow down what's going on. **please scrub all confidential authentication information from the logs before pasting them here :)**

**Comment by pierreca** [comment]
@sanket-kulkarni-vmware I just spent the whole day trying to figure out a breaking change in the `amqp10` library that prevents us from upgrading their latest iteration. Since the problem appears to be in `amqp10` I think it's a good practice for us to upgrade, ship you a new package that depends on the latest version and have you repro with the latest version before asking them for help. I'll keep you posted.

**Comment by pierreca** [comment]
@sanket-kulkarni-vmware I published iothub-explorer@1.1.6 that uses the latest event hubs and amqp10 library versions, can you please give this a go and paste the logs here if the problem reproes (or let us know if it doesn't)? especially the full debug logs around the failure (setting the `DEBUG` env variable to `*` as mentionned in an earlier comment) would help.

**Comment by sanket-kulkarni-vmware** [comment]
@pierreca: I have reinstalled the iothub-explorer tool and now I am not facing this issue. Not sure whats the reason for it.

**Comment by pierreca** [comment]
@sanket-kulkarni-vmware well that's good news. Between v3.2.2 and 3.4.1 there were many improvements to the connection layer of the `amqp10` library so it might include the bugfix for your issue. In any case, since you're not seeing the problem anymore I'm closing the issue but feel free to reopen it if you hit it again, and we'll investigate more.
