### ISSUE TITLE
Using  "connection-string" to generate a "connection-string" does not work

### ISSUE THREAD

**Issue by jamesjara** [Azure/iothub-explorer#9]
Why windows stuff never work first-way...so frustrated, I can't generate my connection string, which looks like the "connection-string" in the portal.azure, is not the real connection-string, you should change the name it is wrong!  

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-getstarted

> Add a connectionString variable and use it to create a Client instance. Replace {youriothostname} with the name of the IoT hub you created the Create an IoT Hub section. Replace {yourdevicekey} with the device key value you generated in the Create a device identity section:

This is not true at all, you must to:

> This worked because, as explained in Control access to IoT Hub: The only way that IoT Hub authenticates a specific device is using the device identity symmetric key. In cases when a shared access policy is used to access device functionality, the solution must consider the component issuing the security token as a trusted subcomponent. Generating the SAS from a prebuilt version of Device explorer.

Device explorer, other windows tool.. we don't use windows, so first problem.ok lets use iothub-explorer,
1. Copy the "connection-string" to generate a "connection-string" .....
2. login
iothub-explorer login "HostName=thermo.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=fUNLK3JJxEQo95ZgOgJSrMXEofqnfAP7/JRjVw9qcHk="
this is creating a session which never works!

Everything give me 401, so what can I do. Docs are not working.....

response:
`header: 'GET /devices/aja?api-version=2016-11-14 HTTP/1.1\r\nAuthorization: SharedAccessSignature sr=thermo.azure-devices.net&sig=tpuca4p6rhBMa%2FislixN6V%2BOSk%2BMNXQ7oChXsB1GMB4%3D&skn=registryReadWrite&se=1486954033\r\nRequest-Id: 24f7fb9c-d951-43a6-a191-0b539573593f\r\nUser-Agent: azure-iothub/1.1.6\r\nHost: thermo.azure-devices.net\r\nConnection: close\r\n\r\n',
`

I'm using the following snippet to generate the SAS:
 ```
var connectionString = 'HostName=thermo.azure-devices.net;SharedAccessKeyName=registryReadWrite;SharedAccessKey=uEzyH+a+dzEvldwsOW/iS1UXqk2e7BgT+Et2wXcMh2U=';
var endpoint ="thermo.azure-devices.net"
var policyName = 'registryReadWrite';
var policyKey = 'uEzyH+a+dzEvldwsOW/iS1UXqk2e7BgT+Et2wXcMh2U=';
var token = generateSasToken(endpoint, policyKey, policyName, 60);
function generateSasToken(resourceUri, signingKey, policyName, expiresInMins) {
  resourceUri = encodeURIComponent(resourceUri);
  // Set expiration in seconds
  var expires = (Date.now() / 1000) + expiresInMins * 60;
  expires = Math.ceil(expires);
  var toSign = resourceUri + '\n' + expires;
  // Use crypto
  var hmac = crypto.createHmac('sha256', new Buffer(signingKey, 'base64'));
  hmac.update(toSign);
  var base64UriEncoded = encodeURIComponent(hmac.digest('base64'));
  // Construct autorization string
  var token = "SharedAccessSignature sr=" + resourceUri + "&sig="
  + base64UriEncoded + "&se=" + expires;
  if (policyName) token += "&skn="+policyName;
  return token;
};
```
Source code: https://github.com/jamesjara/azure-iot-hub-device-js-node/blob/master/CreateDeviceIdentity.js

**Comment by pierreca** [comment]
@jamesjara I think there are 2 separate issues

**1. your code won't create a device identity in the device registry**
I'm not sure what misled you here but I can see [line 13](https://github.com/jamesjara/azure-iot-hub-device-js-node/blob/master/CreateDeviceIdentity.js#L13) that you are concatenating the token you're generating with the connection string. You don't need to do that because the SDK will take care of creating the token for you: the only thing you need to pass is the connection string itself.  if  you remove "+token" from your code, it should just work. 

**2. iothub-explorer is not working you're expecting it to**
`iothub-explorer login <connection-string>` will indeed create a session that should work for 1 hour for all operations except `monitor-events` and `monitor-ops` (because those connect to the event hubs endpoint). If you're getting 401s it may mean that the session is expired or the connection string is incorrect. What you can do to avoid the whole session thing is pass the connection string directly to the command using the `--login` argument.

For example here is the command that lets you get a device description, including the device connection string:
```
iothub-explorer get <device-id> --connection-string --login <iothub-connection-string>
```

The equivalent using the session is:
```
iothub-explorer login <iothub-connection-string>
iothub-explorer get <device-id> --connection-string
```


Maybe to help clear some confusion, you seem to be saying the doc is wrong because it's telling you to use the symmetric key of the device instead of using a shared access signature (SAS). It's not: when you're using the `fromConnectionString` factory method, the SDK generates the SAS for you. when you're using the `fromSharedAccessSignature` method, then you have to generate the SAS yourself. 

Lastly I have created a pull-request in the docs to add a reference iothub-explorer on top of the DeviceExplorer tool because like you said, not everybody uses windows. hope that helps!

**Comment by jamesjaraGL** [comment]
@pierreca I tried also just the connection string, but always getting the 401, like one year ago, trying to use documentDb I had a similar problem, because I was using a wrong date, so I have verify the SAS se parameter in the http request header and looks, so I don't know what could be missing out, could you try clone my git, and change the string connection for the string connection from you policy in portal azure.. if it works, can you paste your http request headers, so we can compare the request

**Comment by pierreca** [comment]
Let's slow down, one problem at a time because I don't understand which one you're referring to. If both iothub-explorer and the script to create the device are failing with 401s it does sound like a system time issue.

Let's get the obvious out of the way first: is your system set to the correct date/time/timezone? can you paste the output of the `date` command from a terminal?

second, let's tackle the problem of iothub-explorer because it's going to help us down the road. Let's start with a simple attempt to list devices on your hub. Can you paste the console session of trying to run this:
```
iothub-explorer list --login <iothub-connection-string>
```
if the system time is correct and you're still getting a 401, let's try these 3 commands in a row and paste the console log here:
```
date
iothub-explorer login <iothub-connection-string>
cat ~/.iothub-explorer
```

Once we get iothub-explorer to work, the rest of the code will be piece of cake.

**Comment by pierreca** [comment]
@jamesjara just thought of something else. We have this tool: https://github.com/Azure/iothub-diagnostics
that you can also install from NPM as the `iothub-diagnostics` package

It might help diagnose connectivity issues, can you try and run it? it just takes your iothub connection string as argument and tries to create a device and use all protocols to send/receive messages to/from it.

**Comment by pierreca** [comment]
@jamesjara we usually close issues after some time of inactivity, assuming either the problem is solved or not worth solving anymore, please let us know if there's something we can do - I'm leaving it open for now but will close it in a couple of days. You should feel free to reopen it if anything new comes up anyway.

**Comment by tameraw** [comment]
@jamesjara - Let us know if still having issues. Regards.
